/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nitc.auction.site;

/**
 *
 * @author girik
 */
public class BidderDashboard extends javax.swing.JFrame {

    String userId ="";
    String type = "";
    public BidderDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        UpdateProfile = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        BidProduct = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 5));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setText("Winner");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 30, 70, 25);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 180, 90));

        Logout.setBackground(new java.awt.Color(153, 153, 153));
        Logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 5));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 0));
        jLabel13.setText("Logout");
        Logout.add(jLabel13);
        jLabel13.setBounds(60, 30, 70, 25);

        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 60, 180, 90));

        UpdateProfile.setBackground(new java.awt.Color(153, 153, 153));
        UpdateProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 5));
        UpdateProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateProfileMouseClicked(evt);
            }
        });
        UpdateProfile.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 0));
        jLabel11.setText("Update Profile");
        UpdateProfile.add(jLabel11);
        jLabel11.setBounds(30, 30, 130, 25);

        getContentPane().add(UpdateProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 180, 90));

        BidProduct.setBackground(new java.awt.Color(153, 153, 153));
        BidProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 5));
        BidProduct.setMinimumSize(new java.awt.Dimension(247, 138));
        BidProduct.setName(""); // NOI18N
        BidProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BidProductMouseClicked(evt);
            }
        });
        BidProduct.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("Bid Product");
        BidProduct.add(jLabel5);
        jLabel5.setBounds(40, 30, 110, 25);

        getContentPane().add(BidProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 180, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/auction/image/hand-that-holds-hammer-piles-money-written-with-white-chalk-draw-concept (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BidProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BidProductMouseClicked
        Bidding bd=new Bidding();
        bd.bidderId=userId;
        bd.type=type;
        bd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BidProductMouseClicked

    private void UpdateProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateProfileMouseClicked
        BidderUpdateProfiles up = new BidderUpdateProfiles();
        up.userId=userId;
        up.type=type;
        up.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UpdateProfileMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        SeeWinner sw = new SeeWinner();
        sw.BidderId = userId;
        sw.type = type;
        sw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BidderDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BidderDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BidderDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BidderDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BidderDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BidProduct;
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel UpdateProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
