/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nitc.auction.site;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author girik
 */
public class ManageSubCategories extends javax.swing.JFrame {
    
    Admin admin=new Admin();
    
    public ManageSubCategories() {
        initComponents();
        SetCategory();
        ShowCategory();
    }
    
    
     public void ShowCategory(){
         DefaultTableModel tableModel;
         tableModel=(DefaultTableModel) catTable.getModel(); 
         int rows = tableModel.getRowCount(); 
         for(int i = rows - 1; i >=0; i--)
         {
            tableModel.removeRow(i); 
         }
        ResultSet rss = admin.showSubCategory();
         try {
            while(rss.next())
            {

                String category=rss.getString("category_type");
                
                String subCategoryId=rss.getString("subcategory_id");
                String subCategoryName=rss.getString("subcategory_name");
                String tableData[]={category,subCategoryId,subCategoryName};
                
                tableModel.addRow(tableData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(RemoveProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void SetCategory()
    {
        
        try {
            Connection con=DBConnection.connectDB();
            PreparedStatement st=con.prepareStatement("select * from category");
            ResultSet rss = (java.sql.ResultSet) st.executeQuery();
             while(rss.next()){
                try {
                    catType.addItem(rss.getString("catName"));
                } catch (SQLException ex) {
                    Logger.getLogger(ManageSubCategories.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageSubCategories.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        catadd1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        catName = new javax.swing.JTextField();
        catId = new javax.swing.JTextField();
        catadd = new javax.swing.JButton();
        catupdt = new javax.swing.JButton();
        catdelete = new javax.swing.JButton();
        catclr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        catTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        catType = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/auction/image/previous.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 30));

        catadd1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        catadd1.setForeground(new java.awt.Color(255, 0, 0));
        catadd1.setText("X");
        catadd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catadd1MouseClicked(evt);
            }
        });
        getContentPane().add(catadd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 80));
        jPanel1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sub-Category Id");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sub-Category Name");

        catName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        catName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catNameActionPerformed(evt);
            }
        });

        catId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        catId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catIdActionPerformed(evt);
            }
        });

        catadd.setBackground(new java.awt.Color(0, 0, 0));
        catadd.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        catadd.setForeground(new java.awt.Color(255, 255, 255));
        catadd.setText("Add");
        catadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddSubCategory(evt);
            }
        });

        catupdt.setBackground(new java.awt.Color(0, 0, 0));
        catupdt.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        catupdt.setForeground(new java.awt.Color(255, 255, 255));
        catupdt.setText("Update");
        catupdt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateSubCategory(evt);
            }
        });

        catdelete.setBackground(new java.awt.Color(0, 0, 0));
        catdelete.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        catdelete.setForeground(new java.awt.Color(255, 255, 255));
        catdelete.setText("Delete");
        catdelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteSubCategory(evt);
            }
        });
        catdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catdeleteActionPerformed(evt);
            }
        });

        catclr.setBackground(new java.awt.Color(0, 0, 0));
        catclr.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        catclr.setForeground(new java.awt.Color(255, 255, 255));
        catclr.setText("Clear");
        catclr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catclrMouseClicked(evt);
            }
        });
        catclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catclrActionPerformed(evt);
            }
        });

        catTable.setBackground(new java.awt.Color(102, 102, 102));
        catTable.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        catTable.setForeground(new java.awt.Color(255, 255, 255));
        catTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category Type", "Category Id", "Category Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        catTable.setDoubleBuffered(true);
        catTable.setName(""); // NOI18N
        catTable.setRowHeight(40);
        catTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        catTable.setShowGrid(false);
        catTable.setShowHorizontalLines(true);
        catTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(catTable);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Category Type");

        catType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(catType, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catId, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(catdelete)
                        .addGap(33, 33, 33)
                        .addComponent(catclr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(catadd)
                        .addGap(26, 26, 26)
                        .addComponent(catupdt)
                        .addGap(59, 59, 59)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(catType, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(catId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(catName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(catadd)
                            .addComponent(catupdt)
                            .addComponent(catclr)
                            .addComponent(catdelete))))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Manage Sub-Categories");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/auction/image/new background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void catNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catNameActionPerformed

    private void catIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catIdActionPerformed

    private void AddSubCategory(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddSubCategory
        String sql="insert into subcategory values(?,?,?,?)";
        if(catId.getText().isEmpty() || catName.getText().isEmpty())
        JOptionPane.showMessageDialog(this,"Missing Information");

        try {
            Connection con=DBConnection.connectDB();
            PreparedStatement st=(PreparedStatement)con.prepareStatement(sql);
            st.setString(1,catId.getText());
            st.setString(2,catName.getText());
            st.setString(3,catType.getSelectedItem().toString());
            
           
            PreparedStatement stt=con.prepareStatement("select * from category");
            ResultSet rss = (java.sql.ResultSet) stt.executeQuery();
            while(rss.next()){
                try {
                    if(rss.getString("catName").equals(catType.getSelectedItem().toString()))
                    {
                        st.setString(4, rss.getString("catId"));
                        break;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ManageSubCategories.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            st.executeUpdate();
            ShowCategory();
            JOptionPane.showMessageDialog(this,"Added Successfully");
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(ManageCategories.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddSubCategory

    private void UpdateSubCategory(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateSubCategory
        if(catId.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "Missing Information");

        try {
            Connection con=DBConnection.connectDB();
            String query="update subcategory set subcategory_name='"+catName.getText()+"',category_type='"+catType.getSelectedItem().toString()+"' where subcategory_id='"+catId.getText()+"'";
            java.sql.Statement st;
            st = con.createStatement();
            st.executeUpdate(query);
            ShowCategory();
            JOptionPane.showMessageDialog(this,"Updated successfully");
        } catch (SQLException ex) {
            Logger.getLogger(ManageCategories.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_UpdateSubCategory

    private void DeleteSubCategory(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteSubCategory
        if(catId.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "Select a subcategory to delete");
        else{
            try{
                Connection con=DBConnection.connectDB();
                
                
                java.sql.Statement st = con.createStatement();
                int executeUpdate = st.executeUpdate("delete from subcategory where subcategory_id='"+catId.getText()+"'");
                ShowCategory();
                JOptionPane.showMessageDialog(this,"Deleted successfully");
            }catch(HeadlessException | NumberFormatException | SQLException ex){
                Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_DeleteSubCategory

    private void catdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catdeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catdeleteActionPerformed

    private void catclrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catclrMouseClicked
        catId.setText("");
        catName.setText("");

    }//GEN-LAST:event_catclrMouseClicked

    private void catTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)catTable.getModel();
        int row = catTable.getSelectedRow();
        catType.setSelectedItem(model.getValueAt(row, 0).toString());
        catId.setText(model.getValueAt(row, 1).toString());
        catName.setText(model.getValueAt(row, 2).toString());
    }//GEN-LAST:event_catTableMouseClicked

    private void catadd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catadd1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_catadd1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new AdminDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void catclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catclrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catclrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSubCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSubCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSubCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSubCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageSubCategories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField catId;
    private javax.swing.JTextField catName;
    private javax.swing.JTable catTable;
    private javax.swing.JComboBox<String> catType;
    private javax.swing.JButton catadd;
    private javax.swing.JButton catadd1;
    private javax.swing.JButton catclr;
    private javax.swing.JButton catdelete;
    private javax.swing.JButton catupdt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
