/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nitc.auction.site;

/**
 *
 * @author girik
 */
public class SellerDashboard extends javax.swing.JFrame {

    String suserId="";
    public SellerDashboard() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateProfile = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        viewProduct = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        catadd1 = new javax.swing.JButton();
        Logout = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        BidHistory = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        SellProduct = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UpdateProfile.setBackground(new java.awt.Color(153, 153, 153));
        UpdateProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 5));
        UpdateProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        UpdateProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateProfileMouseClicked(evt);
            }
        });
        UpdateProfile.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 0));
        jLabel11.setText("Update Profile");
        UpdateProfile.add(jLabel11);
        jLabel11.setBounds(20, 30, 130, 25);

        getContentPane().add(UpdateProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, 90));

        viewProduct.setBackground(new java.awt.Color(153, 153, 153));
        viewProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 5));
        viewProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewProductMouseClicked(evt);
            }
        });
        viewProduct.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 0));
        jLabel9.setText("View Product");
        viewProduct.add(jLabel9);
        jLabel9.setBounds(30, 30, 120, 25);

        getContentPane().add(viewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 180, 90));

        catadd1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        catadd1.setForeground(new java.awt.Color(255, 0, 0));
        catadd1.setText("X");
        catadd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catadd1MouseClicked(evt);
            }
        });
        getContentPane().add(catadd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, -1, -1));

        Logout.setBackground(new java.awt.Color(153, 153, 153));
        Logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 5));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 0));
        jLabel13.setText("Logout");
        Logout.add(jLabel13);
        jLabel13.setBounds(60, 30, 70, 25);

        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 40, 180, 90));

        BidHistory.setBackground(new java.awt.Color(153, 153, 153));
        BidHistory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 5));
        BidHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BidHistoryMouseClicked(evt);
            }
        });
        BidHistory.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 0));
        jLabel7.setText("Bidding History");
        BidHistory.add(jLabel7);
        jLabel7.setBounds(20, 30, 140, 25);

        getContentPane().add(BidHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 180, 90));

        SellProduct.setBackground(new java.awt.Color(153, 153, 153));
        SellProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 5));
        SellProduct.setForeground(new java.awt.Color(153, 153, 153));
        SellProduct.setToolTipText("");
        SellProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellProductMouseClicked(evt);
            }
        });
        SellProduct.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(51, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Sell Product");
        SellProduct.add(jLabel2);
        jLabel2.setBounds(30, 30, 110, 25);

        getContentPane().add(SellProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 180, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/auction/image/hand-that-holds-hammer-piles-money-written-with-white-chalk-draw-concept (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void catadd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catadd1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_catadd1MouseClicked

    private void SellProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellProductMouseClicked
        Product pr=new Product();
        pr.userId=suserId;
        pr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SellProductMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
       new Login().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void viewProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewProductMouseClicked
        RemoveProduct rp =new RemoveProduct();
        rp.ruserId=suserId;
        rp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewProductMouseClicked

    private void BidHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BidHistoryMouseClicked
        BiddingInformation bi = new BiddingInformation();
        bi.sellerId=suserId;
        bi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BidHistoryMouseClicked

    private void UpdateProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateProfileMouseClicked
        UpdateProfiles up = new UpdateProfiles();
        up.userId=suserId;
        up.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UpdateProfileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BidHistory;
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel SellProduct;
    private javax.swing.JPanel UpdateProfile;
    private javax.swing.JButton catadd1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel viewProduct;
    // End of variables declaration//GEN-END:variables
}
